-- Add USER_ACTIVATED, USER_DEACTIVATED, USER_INVITED, USER_INVITE_REVOKED to AuditEventType enum  
ALTER TYPE "AuditEventType" ADD VALUE 'USER_ACTIVATED';  
ALTER TYPE "AuditEventType" ADD VALUE 'USER_DEACTIVATED';  
ALTER TYPE "AuditEventType" ADD VALUE 'USER_INVITED';  
ALTER TYPE "AuditEventType" ADD VALUE 'USER_INVITE_REVOKED'; 
