// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load local env files in order of precedence.
dotenv.config({ path: ".env.local" });
dotenv.config({ path: ".env" });

function getDatabaseUrl(): string | undefined {
  const url = process.env["DATABASE_URL"];
  if (!url) return url;

  try {
    const parsed = new URL(url);
    // Supabase transaction pooler requires pgbouncer mode and a single
    // connection for Prisma schema-engine commands.
    if (parsed.hostname.includes("pooler.supabase.com")) {
      parsed.searchParams.set("pgbouncer", "true");
      parsed.searchParams.set("connection_limit", "1");
      return parsed.toString();
    }
  } catch {
    // Ignore malformed URLs and fall back to the raw value.
  }

  return url;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] || undefined,
  },
});
